### PR TITLE
Story/VSPC-48_1

### PR DESCRIPTION
**Pull request by prjadhav14**
Creating new PR as a force push was required to resolve conflicts with develop branch.

### CODE REVIEW

**Comment by jdamerow** [comment]
you shouldn't need to force push. Did you merge develop and resolve all conflicts?

**Comment by jdamerow** [comment]
Jenkins, test this please.

**Comment by jdamerow** [comment]
Almost there, just a few small things:
 - the box with the space description should have a little more padding so the text is a little bit further away from the box border
- the list of modules should use the 'i' icon as bullets
image
- if there is no label for a module link, it should use the title of the module, otherwise the module doesn't show up in the list

**Comment by prjadhav14** [comment]
> you shouldn't need to force push. Did you merge develop and resolve all conflicts?

The file having conflicts had same changes on both the branches. So I updated the files and resolved conflicts the code was getting pushed but the changes were not coming up on the same PR. So, I did force push. The conflicts are resolved. This is the case with Story-72 as well as the same file(skeleton_exhibition2.jsp) is modified.

**Comment by jdamerow** [comment]
Jenkins, test this please.

**Comment by jdamerow** [comment]
almost there. the 'i' is not the same as the icon:
image

**Comment by jdamerow** [comment]
Jenkins, test this please.

**Comment by jdamerow** [comment]
"if there is no label for a module link, it should use the title of the module, otherwise the module doesn't show up in the list"

It shows the module id right now.

but so close!!!

**Comment by jdamerow** [comment]
Hurray!

**Pull request merged**
