### PR TITLE
[VSPC-93] Creating new branch and added code changes

### PR DESCRIPTION
**Pull request by ashmichheda**
- Created a new branch to resolve all the code merge conflicts that occurred in `story/VSPC-93` and other unix code endings issues that developed in the branch.

### CODE REVIEW

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
This doesn't look right:
image

**Comment by ashmichheda** [comment]
You mean the design of the menu is not right?

**Comment by jdamerow** [comment]
The whole space image is moved way down almost out of sight and the menu has a grey background.

**Comment by ashmichheda** [comment]
Okay, I will fix that. Thanks

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Not much seemed to have changed. Image is still way too low, the menu icon button has a grey background, and when the menu is open, the menu button needs to be hidden and a close button needs to be shown instead.

**Comment by ashmichheda** [comment]
On my local in chrome browser, I am able to move up the image closer to the menu. Also, the grey background has been removed. Are you getting something different than this?

image

**Comment by jdamerow** [comment]
I did. If you want to check it out, just reopen the PR. I'm fairly certain I made sure to not used cached files, but I can try again.

**Comment by ashmichheda** [comment]
I think, you are still referring to the other `story/VSPC-93` branch for checking the new changes. Maybe that's the reason why you didn't find anything changed. 
I have created another branch, this one for all the latest changes.

**Comment by jdamerow** [comment]
Make it so, Jenkins.

**Comment by jdamerow** [comment]
Nothing has changed in regards to the image position: https://diging-dev.asu.edu/vspace-dev/exhibit/space/SPA2
Also, the close button for the menu should be the 'x' it was before.

**Comment by ashmichheda** [comment]
Is this coming in Mobile or Desktop?

**Comment by jdamerow** [comment]
Image and menu icon need to go further up. And the menu should open above the background image on regular screens, not pushing it down:
image
also on small screens the menu is open by default with the menu icon shown and when I click on the menu icon, the complete menu plus icon disappers.

**Pull request closed without merging**
