### PR TITLE
Story/vspc 59

### PR DESCRIPTION
**Pull request by Neehaarika**
I have made sure the images smaller than div width are made fit to the div of the content block. Let me know your comments on it.

### CODE REVIEW

**Comment by jdamerow** [comment]
Jenkins, test this please.

**Comment by jdamerow** [comment]
Now the links aren't in the right position anymore.

**Comment by jdamerow** [comment]
Jenkins, test this please.

**Comment by jdamerow** [comment]
this doesn't seem to work. when I first load the page I see this:
image
when I shift-relaod I see this:
image

**Comment by Neehaarika** [comment]
I did not change much but now on shift refresh pics are not getting enlarged. Please review.

**Comment by jdamerow** [comment]
Jenkins, test this please.

**Comment by jdamerow** [comment]
images are blown up again, so that they are bigger than their actual size:
image

**Comment by jdamerow** [comment]
the textboxes are now resized as well:
image

**Comment by jdamerow** [comment]
If I add a new image, it's not being resized. I have to reload the page so it is set to the page width.

**Comment by jdamerow** [comment]
oh glory day! ;)

**Comment by jdamerow** [comment]
[VSPC-59] #accepted

**Pull request merged**
