### PR TITLE
Story/VSPC-79

### PR DESCRIPTION
**Pull request by prjadhav14**

### CODE REVIEW

**Comment by jdamerow** [comment]
i'm confused,  this is for VSPC-79, isn't it ("Delete space link is broken")? this code seems to be about deleting spaces, which is VSPC-49.

**Comment by jdamerow** [comment]
did you misunderstand the ticket?

**Comment by prjadhav14** [comment]
> did you misunderstand the ticket?

I think so. :-(
I worked on deleting spaces.

**Comment by jdamerow** [comment]
Jenkins, test this please.

**Pull request merged**
