### PR TITLE
Story/vspc 141

### PR DESCRIPTION
**Pull request by swetalina-prusty25**
# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

the search should search all spaces (title, description), all modules (title, description), and all slides (title, text blocks). the user should be able to go directly to a found element.
  
## Anything else the reviewer needs to know?

... describe here ...

### CODE REVIEW

**Comment by jdamerow** [comment]
Resolve conflicts please

**Comment by jdamerow** [comment]
This looks like a bunch of changes are being reverted (probably wrongly merged)?

**Comment by pkharge** [comment]
@jdamerow, could you refer to the changes you suspect? the commit diff contains a lot of changes just due to change in formatting in develop. I have tested search feature post merging and it seems fine.

**Comment by pkharge** [comment]
@jdamerow could you refer to the changes you suspect? the commit diff contains a lot of formatting changes from develop. Search feature seems to work fine post merge. 
Although I do see a previous merge c1dbf0fc18ba13fed7a8a5e5f699c2ad999df0ba into this branch which has reverted some of the changes from this merged PR.  https://github.com/diging/virtual-spaces-2.0/pull/227. Not sure if you are referring to this.

**Comment by jdamerow** [comment]
I didn’t get very far but for example: 
- typo in read me is reintroduced
- code related to module status is being removed

**Pull request closed without merging**
